config/routes.rb
Pipeline::Application.routes.draw do

  get "comments/index"
  get "comments/new"
  %w[about intro privacy terms contact].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",registrations: "registrations"}

  resources :users , only: [:index, :show, :edit,:update]

  resources :labs, :papers
  resources :gurus, only: [:new, :create,  :edit, :update, :destroy]

  concern :photoable do
    resources :photos, only: [:index, :new, :create, :show, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:index, :new, :create, :show, :destroy]
  end

  # resources :articles, concerns: :sociable
  resources :programs, concerns: [:photoable, :commentable]
  resources :papers , concerns: :commentable

  resources :articles do
    concerns :commentable
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    collection { get :search, to: 'articles#search' }
  end

  resources :events do
    concerns :commentable
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"
    end
    collection { get :search, to: 'events#search' }
  end

  resources :categories, only: [:index]

  get 'trends/:group', to: 'articles#index', as: :group

  get "welcome/index"

  root 'welcome#index'



end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :photos, as: :attachable
  has_many :comments, as: :commentable
  has_many :groups, through: :groupings
  has_many :groupings

  validates :title, presence: true
  validates :user_id, presence: true
  mount_uploader :image, ImageUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_readonly :comments_count

  scope :trending,  lambda { |num = nil| includes(:user).order('created_at  desc').limit(num) }
  scope :hot,  lambda { |num = nil| includes(:user).order('cached_votes_up  desc').limit(num) }
  scope :available,  lambda { |num = nil| includes(:user).limit(num) }

  acts_as_votable


  # def self.cached_published
  #   # updated_at = published.maximum(:updated_at)
  #   Rails.cache.fetch([name, "published"], expires_in: 5.minutes) do
  #     published.to_a
  #   end
  # end


  def self.search(query)
    trending.where("title like ?", "%#{query}%")
  end

  def self.search_tags(keywords, group_id)
    articles = Article.available
    articles = articles.where("title like ?", "%#{keywords}%") if keywords.present?
    articles = articles.includes(:groups).where("groups.id = ?", group_id).references(:groups) if group_id.present? and group_id !=""
    articles
  end

  def self.group_with(name)
    available.includes(:groups).where("groups.name = ?", name).references(:groups)
  end

  def group_list
    groups.map(&:name).join(", ")
  end

  def to_param
    "#{id}-#{title}".parameterize
  end

  def self.trends(num)
    if num.present?
      hot.limit(num)
    else
      hot
    end
  end

  def to_writer
     "By #{user.username} #{created_at.strftime("%B %d, %Y")}".titleize
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index

  end

  def search

  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article , notice: 'Program was successfully created'
    else
      render 'new'
    end
  end

  def show
    @commentable = @article
    @comment = Comment.new
    @attachable = @article
    @photos = @attachable.photos
    @voter = current_user

  end

  def edit

  end

  def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Program was successfully updated.'
      else
        render  'edit'
      end
  end

  def destroy
    @article.destroy
    redirect_to articles_url
  end

  def upvote

    respond_to do |format|
      if @article.liked_by current_user
        format.html { redirect_to @article, notice: "Thanks for vote!" }
        format.js
      else
        render @article
      end
    end
  end

  def downvote

    respond_to do |format|
      if  @article.downvote_from current_user
        format.html { redirect_to @article, notice: "Thanks for vote!" }
        format.js
      else
        render @article
      end
    end
  end


private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :image,:group_ids=>[])
  end

  def groups
    # @groups ||= Group.order(:name)
    @groups ||= Group.cached_groups
  end

  helper_method :groups


  def articles
    if params[:group]
      @articles = Article.group_with(params[:group]).page(params[:page]).per(10)
    elsif params[:q] || params[:group_id]
      @articles ||= Article.search_tags(params[:q], params[:group_id]).page(params[:page]).per(10)
    else
      @articles ||= Article.trends('100').page(params[:page]).per(10)
    end

  end

  helper_method :articles
end

app/helpers/articles_helper.rb
module ArticlesHelper



end

app/views/articles/_article.html.erb
<% articles.each do |article| %>
 <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="thumbnail docs-container ">
          <div class="media">
            <h4 class="media-heading"><%= link_to article.title.titleize, article , :class=>'post-title' %></h4>
            <div class="media-body">
                <% if article.image.present? %>
                  <div class="focal-point imagebox right-1 up-1">
                    <div> <%= link_to image_tag(article.image.url(:mobile), :class=> 'media-object') , article %></div>
                  </div>
                <% end %>
            </div>

          </div>
          <div class="media">
            <p class="pull-left" >
             <%= image_tag( article.user.image.url(:thumb), :class=>'media-object img-circle' ,:size=>'32x32') %>
            </p>
            <h4 class="writer">
              <p><%= article.to_writer %> </p>
              <p><%= pluralize(article.comments_count, "Comment") %>
              <%= pluralize(article.cached_votes_up, "Like") %></p>
            </h4>
          </div>
      </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for  @article , :html => { :id=>'article_editor' , :multipart=>true, :class=>'form-horizontal'} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
            <%= f.label 'Keywords', :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
     <%= f.collection_select :group_ids, Group.order(:name), :id, :name, {}, {id:'article_group' , multiple:true, class: 'form-control info myselect'} %>
      </div>

    </div>
    <div class="form-group">
      <%= f.label :title, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, :class => 'form-control', :placeholder=>"Title" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :content, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :content, :class => 'form-control', :placeholder=>"Content" , :rows=>"10"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :image, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
      <%= f.file_field :image, :class => '', :placeholder=>"jpg, gif, png only"%>
      <%= f.hidden_field :image_cache %>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit nil, :class=> "btn btn-default" %>
        <%= link_to 'Cancel', articles_path, :class => "btn btn-default" %>
      </div>
    </div>

<% end %>

app/views/articles/_search.html.erb
<%= form_tag search_articles_path, :method => :get  , :class=>'form-inline' do  %>
  <div class="form-group">
    <%= text_field_tag :q, params[:q], :class => "form-control", :placeholder=>"Keywords"  %>
  </div>
  <div class="form-group">
    <%= select_tag "tag_id", options_from_collection_for_select(tags, :id, :name,:selected=> params[:tag_id]), include_blank: true,  class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= submit_tag "Search", :name => nil ,:class => 'btn btn-default' %>
  </div>
<% end %>

app/views/articles/_tag_cloud.html.erb
<div class="row tag_cloud">
  <ul class="">
  <%= link_to 'All', articles_path ,class: "label label-info tags" %>
  <%  groups.each do |group| %>
  <%= link_to group.name, group_path(group.name), class: tag_class(group.level) %>
  <% end %>
  </ul>
</div>

app/views/articles/_tag_items.html.erb
<ul>
<% tags.each do |tag| %>
<%=  content_tag :li, class: tag_class(tag.level) do
    tag.name
  end %>
<% end%>
</ul>

app/views/articles/downvote.js.erb
$("#vote").html("<%=j pluralize(@article.cached_votes_up, 'Like') %>")

$("#btn_like").show();
$("#btn_dislike").hide();

app/views/articles/edit.html.erb
<h3 class="page-header">Edit article</h3>

<%= render 'form' %>

app/views/articles/index.html.erb
<h4 class="page-header">Dash Board
<%= link_to  'Search or Add New' , '#' , :id => 'article-search' ,:class =>"btn btn-link" %>
<%= link_to  'Close' , '#' , :id => 'article-search-off' ,:class =>"btn btn-link" %> </h4>

<%= render 'tag_cloud' %>
<div id="tag_panel">
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-4">
    <%= link_to 'New article', new_article_path ,:class => 'btn btn-default' %>
  </div>
  <div class="col-xs-12 col-sm-8 col-md-8 text-right ">
      <%= render 'search' %>
  </div>
</div>
<h3></h3>
</div>
<% cache "Article" , expires_in: 5.minutes do %>
<div id="articles" class="row">
<%= render partial: "article", locals: { articles:  articles   } %>
</div>

<%= paginate articles  %>
<% end %>

app/views/articles/index.js.erb
$('#articles').append('<%= j render partial: "article", locals: { items: articles } %>');

<% if articles.next_page %>
$('.pagination').replaceWith('<%= j paginate(articles) %>');
<% else %>
$('.pagination').remove();
<% end %>

app/views/articles/new.html.erb
<h3 class="page-header">New article</h3>

<%= render 'form' %>

app/views/articles/search.html.erb
<% content_for :slidebar do %>
  <%= render 'tag_cloud' %>
<% end %>
<h3 id="" class="page-header">Dash Board</h3>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-4">
    <%= link_to 'New article', new_article_path ,:class => 'btn btn-default' %>
  </div>
  <div class="col-xs-12 col-sm-8 col-md-8 text-right ">
      <%= render 'search' %>
  </div>
</div>
<h3></h3>

<div  id="articles" class="row">
 <%= render partial: "article", locals: { articles:  articles  } %>
</div>

<%= paginate articles %>

app/views/articles/search.js.erb
$('#articles').append('<%= j render partial: "article", locals: { items: articles } %>');

<% if articles.next_page %>
$('.pagination').replaceWith('<%= j paginate articles %>');
<% else %>
$('.pagination').remove();
<% end %>

app/views/articles/show.html.erb
<% content_for :slidebar do %>
  <div class="article">
    <p><h3 class="text-center"><%= @article.title.titleize %></h3></p>
    <h4 class="writer text-center"> <%= @article.to_writer %></h4>
    <%=render 'tag_items', {tags: @article.groups } %>
  </div>

<% end %>

<div class="row">
  <div class="">
    <p> <%= @article.content %></p>
  </div>
  <div class="">
    <p> <%= @article.group_list %></p>
  </div>
  <div class="focal-point right-1 up-1">
    <div> <%= image_tag @article.image.url(:mobile), :class =>'thumbnail' if @article.image.present? %></div>
  </div>
  <div id="vote" class="col-xs-12  col-sm-12 col-md-12">
    <%= pluralize(@article.cached_votes_up, "Like") %>
  </div>

  <div class="col-xs-12  col-sm-12 col-md-12">

  <%= link_to 'Back',params[:q] ? :back : articles_path %>

  <%= link_to 'Edit', edit_article_path(@article) if current_user?(@article.user)  %>
  <%= link_to "Like", like_article_path(@article), method: :put ,id:'btn_like', remote: true , :style => @voter.voted_up_on?(@article) ?  'display: none;' : 'display: inline;'   %>
  <%= link_to "Dislike", dislike_article_path(@article), method: :put ,id:'btn_dislike', remote: true , :style => @voter.voted_up_on?(@article) ?  'display: inlinie;' : 'display: none;'    %>
  <%= link_to pluralize(@article.comments_count, "Comment"),  article_comments_path(@article)  %>
  </div>
</div>

app/views/articles/upvote.js.erb
$("#vote").html("<%=j pluralize(@article.cached_votes_up, 'Like') %>")

$("#btn_like").hide();
$("#btn_dislike").show();