config/routes.rb
Pipeline::Application.routes.draw do

  get "comments/index"
  get "comments/new"
  %w[about intro privacy terms contact].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",registrations: "registrations"}

  resources :users , only: [:index, :show, :edit,:update]

  resources :labs, :papers
  resources :gurus, only: [:new, :create,  :edit, :update, :destroy]

  concern :photoable do
    resources :photos, only: [:index, :new, :create, :show, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:index, :new, :create, :show, :destroy]
  end

  # resources :articles, concerns: :sociable
  resources :programs, concerns: [:photoable, :commentable]
  resources :papers , concerns: :commentable

  resources :articles do
    concerns :commentable
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    collection { get :search, to: 'articles#search' }
  end

  resources :events do
    concerns :commentable
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"
    end
    collection { get :search, to: 'events#search' }
  end

  resources :categories, only: [:index]

  get 'trends/:group', to: 'articles#index', as: :group

  get "welcome/index"

  root 'welcome#index'



end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :user
  has_many :photos, as: :attachable
  has_many :comments, as: :commentable

  validates :title, presence: true, length: { maximum: 140 }
  attr_readonly :comments_count

  def to_param
    "#{id}-#{title}".parameterize
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @attachable = @program
    @photos = @attachable.photos
    @commentable = @program
    @comments = @commentable.comments.page(params[:page]).per(10)
    @comment = Comment.new
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
  @program = Program.new(program_params)
  @program.user = current_user
    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render action: 'show', status: :created, location: @program }
      else
        format.html { render action: 'new' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:title, :content ,:user_id)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for @program  , :html => { :class => 'form-horizontal' } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    <legend><%= controller.action_name.capitalize %> Program</legend>
      <div class="form-group">
        <%= f.label :title, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, :class => 'form-control', :placeholder=>"Title" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :content, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :content, :class => 'form-control', :placeholder=>"Content" %>
        </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit nil, :class=> "btn btn-default" %>
        <%= link_to 'Cancel', programs_path, :class => "btn btn-default" %>
      </div>
    </div>

<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> | <%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.title %></td>
        <td><%= program.content %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path ,:class => 'btn btn-default' %>

app/views/programs/new.html.erb
<h2>New program</h2>

<%= render 'form' %>

app/views/programs/show.html.erb
<div class="row">
  <%= @program.title %>
</div>
<div class="row">
  <%= @program.content %>
</div>
<div class="row">
<%= link_to pluralize(@program.comments_count, "Comment"),  program_comments_path(@program)  %>
</div>

<div class="row">
  <div id ="photos">
  <% for photo in @photos %>
    <%= render(photo) %>
  <% end %>
  </div>
</div>
<div class="row">
  <%= render 'photos/form_inline' %>
</div>
<div class="row">
  <div class="col-xs-12  col-sm-12 col-md-12">
    <%= link_to 'Edit', edit_program_path(@program) ,:class => 'btn btn-default'%> |

    <%= link_to 'Back', programs_path ,:class => 'btn btn-default'%>
  </div>
</div>