config/routes.rb
Pipeline::Application.routes.draw do

  get "comments/index"
  get "comments/new"
  %w[about intro privacy terms contact].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",registrations: "registrations"}

  resources :users , only: [:index, :show, :edit,:update]

  resources :labs, :papers
  resources :gurus, only: [:new, :create,  :edit, :update, :destroy]

  concern :photoable do
    resources :photos, only: [:index, :new, :create, :show, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:index, :new, :create, :show, :destroy]
  end

  # resources :articles, concerns: :sociable
  resources :programs, concerns: [:photoable, :commentable]
  resources :papers , concerns: :commentable

  resources :articles do
    concerns :commentable
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    collection { get :search, to: 'articles#search' }
  end

  resources :events do
    concerns :commentable
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"
    end
    collection { get :search, to: 'events#search' }
  end

  resources :categories, only: [:index]

  get 'trends/:group', to: 'articles#index', as: :group

  get "welcome/index"

  root 'welcome#index'



end

app/views/shared/_avata.html.erb
<%= image_tag( user.image.url(version), :class=>'thumbnail') %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_item_box.html.erb
<div class="media">
  <h4 class="media-heading"><%= link_to title.titleize, item , :class=>'post-title' %></h4>
  <div class="media-body">
      <div class="crop">
       <%= link_to image_tag(item.image.url(:mobile), :class=> 'place media-object') , item %>
      </div>
  </div>
</div>
<div class="media">
  <h4 class="writer"><%= item.to_writer %></h4>
  <div class="media-body">
    <%= truncate(content , length: 140) if content.present? %>
  </div>
</div>

app/views/shared/_link_to_profile.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><%= link_to "My Profile", current_user, class: "" %></li>
    <li><%= link_to "Settings", edit_user_path(current_user), class: "" %></li>
    <% if current_user.grade =='guru' %>
      <li><%= link_to "Cite Me", papers_path , class: "" %></li>
      <li><%= link_to "Positions", labs_path , class: ""  %></li>
    <% elsif current_user.guru? %>
      <li><%= link_to "Edit a request", edit_guru_path(current_user), class: ""  %></li>
        
    <% else %>

      <li><%= link_to "Apply a mentor", new_guru_path, class: ""  %></li>
    
    <% end  %>
  </ol>
</div>