config/routes.rb
Pipeline::Application.routes.draw do

  get "comments/index"
  get "comments/new"
  %w[about intro privacy terms contact].each do |page|
    get page, controller: "info", action: page
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",registrations: "registrations"}

  resources :users , only: [:index, :show, :edit,:update]

  resources :labs, :papers
  resources :gurus, only: [:new, :create,  :edit, :update, :destroy]

  concern :photoable do
    resources :photos, only: [:index, :new, :create, :show, :destroy]
  end

  concern :commentable do
    resources :comments, only: [:index, :new, :create, :show, :destroy]
  end

  # resources :articles, concerns: :sociable
  resources :programs, concerns: [:photoable, :commentable]
  resources :papers , concerns: :commentable

  resources :articles do
    concerns :commentable
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    collection { get :search, to: 'articles#search' }
  end

  resources :events do
    concerns :commentable
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"
    end
    collection { get :search, to: 'events#search' }
  end

  resources :categories, only: [:index]

  get 'trends/:group', to: 'articles#index', as: :group

  get "welcome/index"

  root 'welcome#index'



end

app/models/event.rb
require 'file_size_validator'

class Event < ActiveRecord::Base
  belongs_to :user
  has_many :photos, as: :attachable
  has_many :comments, as: :commentable

  validates :title, presence: true
  validates :user_id, presence: true
  validates :target, :file_size => { :maximum => 0.5.megabytes.to_i }

  mount_uploader :target, TargetUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_readonly :comments_count

  acts_as_votable
  acts_as_taggable
  acts_as_taggable_on :offers, :interests
  acts_as_followable


  scope :trending,  lambda { |num = nil| includes(:user).order('created_at  desc').limit(num) }
  scope :hot,  lambda { |num = nil| includes(:user).order('cached_votes_up  desc').limit(num) }
  scope :available,  lambda { |num = nil| includes(:user).limit(num) }
  
  def crop_target
    self.target.recreate_versions! if crop_x.present?
  end

  def self.trends(num)
    if num.present?
      hot.limit(num)
    else
      hot
    end
  end

 #  def self.offers
	# # ActsAsTaggableOn::Tag.includes(:taggings).where("taggings.context = 'offers'")
 #  end

  def self.cached_offers
    Rails.cache.fetch([self, "offers"]) { ActsAsTaggableOn::Tag.includes(:taggings).where("taggings.context = 'offers'").to_a }
  end

  def to_param
    "#{id}-#{title}".parameterize
  end

  def to_writer
     "By #{user.username} #{created_at.strftime("%B %d, %Y")}".titleize
  end

  def profile_pic
    user.image.url(:thumb) || 'profile.png'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	before_action :set_event, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def index

	end

	def search

	end

	def new
	@event = Event.new
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
		  redirect_to @event , notice: 'Program was successfully created'
		else
		  render 'new'
		end
	end

	def show
		@commentable = @event
		@comment = Comment.new
		@attachable = @event
		@photos = @attachable.photos
		@voter = current_user
	end

	def edit

	end

	def update
	  if @event.update(event_params)
	    redirect_to @event, notice: 'Program was successfully updated.'
	  else
	    render  'edit'
	  end
	end

	def destroy
		@event.destroy
		redirect_to events_url
	end

	def upvote
		respond_to do |format|
		  if @event.liked_by current_user
		    format.html { redirect_to @event, notice: "Thanks for vote!" }
		    format.js
		  else
		    render @event
		  end
		end
	end

	def downvote
		respond_to do |format|
		  if  @event.downvote_from current_user
		    format.html { redirect_to @event, notice: "Thanks for vote!" }
		    format.js
		  else
		    render @event
		  end
		end
	end

	private

	def set_event
		@event = Event.find(params[:id])
	end

	def event_params
		params.require(:event).permit(:title, :content, :target, :remote_target_url, :crop_x,:crop_y,:crop_w,:crop_h, :tag_list=>[])
	end

	def offers 
		@offers ||= Event.cached_offers
	end

	helper_method :offers

	def events
		if params[:tag]
		  @events = Event.tagged_with(params[:tag]).page(params[:page]).per(10)
		elsif params[:q] || params[:tag_id]
		  @events ||= Event.search_tags(params[:q], params[:tag_id]).page(params[:page]).per(10)
		else
		  @events ||= Event.trends('100').page(params[:page]).per(10)
		end
	end

	helper_method :events
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<% events.each do |event| %>
 <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="thumbnail docs-container ">
          <div class="media">
            <h4 class="media-heading"><%= link_to event.title.titleize, event , :class=>'post-title' %></h4>
            <div class="media-body">
                <% if event.target.present? %>
                  <div class="focal-point imagebox right-1 up-1">
                    <div> <%= link_to image_tag(event.target.url(:mobile), :class=> 'media-object') , event %></div>
                  </div>
                <% end %>
            </div>

          </div>
          <div class="media">
            <p class="pull-left" >
             <%= image_tag(event.profile_pic, :class=>'media-object img-circle' ,:size=>'32x32') %>
            </p>
            <h4 class="writer">
              <p><%= event.to_writer %> </p>
              <p><%= pluralize(event.comments_count, "Comment") %>
              <%= pluralize(event.cached_votes_up, "Like") %></p>
            </h4>
          </div>
      </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for  @event , :html => { :id=>'event_editor' , :multipart=>true, :class=>'form-horizontal'} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
     	<%= f.label 'Offer', :class => 'col-sm-2 control-label' %>
     	<div class="col-sm-10">
     	<%= f.collection_select :tag_list, offers, :name, :name, {}, {id:'event_tag' , multiple:true, class: 'form-control info myselect'} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Destination', :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, :class => 'form-control', :placeholder=>"Title" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :target, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
      <%= image_tag(@event.target_url) if @event.target? %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :target, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
      <%= f.file_field :target, :class => '', :placeholder=>"jpg, gif, png only"%>
      <%= f.text_field :remote_target_url ,:class => 'form-control', :placeholder=>"jpg, gif, png only"%>
      <%= f.hidden_field :target_cache %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :content, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :content, :class => 'form-control', :placeholder=>"Content" , :rows=>"10"%>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit nil, :class=> "btn btn-default" %>
        <%= link_to 'Cancel', events_path, :class => "btn btn-default" %>
      </div>
    </div>

<% end %>

app/views/events/_search.html.erb
<%= form_tag search_events_path, :method => :get  , :class=>'form-inline' do  %>
  <div class="form-group">
    <%= text_field_tag :q, params[:q], :class => "form-control", :placeholder=>"Keywords"  %>
  </div>
  <div class="form-group">
    <%= select_tag "tag_id", options_from_collection_for_select(offers, :id, :name,:selected=> params[:tag_id]), include_blank: true,  class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= submit_tag "Search", :name => nil ,:class => 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h3 class="page-header">Edit Event</h3>

<%= render 'form' %>

app/views/events/index.html.erb
<% content_for :slidebar do %>

<% end %>

<h4 class="page-header">Dash Board </h4>

<div class="row tag_cloud">
  <ul class="">
  <%= link_to 'All', events_path ,class: "label label-info tags" %>
  <% offers.each do |tag| %>
  <%= link_to tag.name, group_path(tag.name), class: tag_class(tag.level) %>
  <% end %>
  </ul>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-4">
    <%= link_to 'New Event', new_event_path ,:class => 'btn btn-default' %>
  </div>
  <div class="col-xs-12 col-sm-8 col-md-8 text-right ">
      <%= render 'search' %>
  </div>
</div>


<div id="articles" class="row">
<%= render partial: "events", locals: { articles:  events   } if events.present? %>
</div>

<%= paginate events  %>

app/views/events/new.html.erb
<h3 class="page-header">New Event</h3>

<%= render 'form' %>

app/views/events/show.html.erb
<% content_for :slidebar do %>
  <div class="article">
    <p><h3 class="text-center"><%= @event.title.titleize %></h3></p>
    <h4 class="writer text-center"> <%= @event.to_writer %></h4>
  </div>

<% end %>

<div class="row">
  <div class="">
    <p> <%= @event.content %></p>
  </div>  
  <div class="focal-point imagebox2 right-1 up-1">
    <%= image_tag @event.target.url(:mobile), :class =>'thumbnail' if @event.target.present? %>
  </div>
  <div class="">
    <p> <%= @event.offer_list %></p>
  </div>

  <div id="vote" class="col-xs-12  col-sm-12 col-md-12">
    <%= pluralize(@event.cached_votes_up, "Like") %>
  </div>

  <div class="col-xs-12  col-sm-12 col-md-12">
  <%= link_to 'Back', :back %>
  <%= link_to 'Edit', edit_event_path(@event) if current_user?(@event.user)  %>
  <%= link_to "Like", like_event_path(@event), method: :put ,id:'btn_like', remote: true , :style => @voter.voted_up_on?(@event) ?  'display: none;' : 'display: inline;'   %>
  <%= link_to "Dislike", dislike_event_path(@event), method: :put ,id:'btn_dislike', remote: true , :style => @voter.voted_up_on?(@event) ?  'display: inlinie;' : 'display: none;'    %>
  <%= link_to pluralize(@event.comments_count, "Comment"),  event_comments_path(@event)  %>
  </div>
</div>